Repository cartesi/rollups-node, pull requests merged in 2023-12, with the labels that each got.

#194 chore: move GraphQL reader API
  api/graphql/reader.graphql
  pkg/readerclient/genqlient.yaml
Labels: no changelog, #feat:rollups-cli

#199 feat: make node ports configurable
  cmd/cartesi-rollups-node/services.go
  internal/config/generate/Config.toml
  internal/config/get.go
Labels: no changelog, #feat:single-container

#207 feat: disable local redis persistence
  cmd/cartesi-rollups-node/services.go
Labels: no changelog, #feat:single-container

#210 fix: service reachability
  build/node-compose.yml
  cmd/cartesi-rollups-node/services.go
Labels: no changelog, #feat:go-supervisor

#215 Update read input(s) command
  pkg/readerclient/generate/input.graphql
  pkg/readerclient/generate/inputs.graphql
  pkg/readerclient/generated.go
  pkg/readerclient/input.go
Labels: no changelog, #feat:rollups-cli

#220 fix: panic when executable not in $PATH
  internal/services/service.go
  internal/services/service_test.go
Labels: bug, no changelog, #feat:go-supervisor
