Repository cartesi/rollups-node, pull requests merged in 2024-02, with the labels that each got.

#300 chore: bump emulator SDK and server-manager
  CHANGELOG.md
  README.md
  build/docker-bake.hcl
  offchain/test-fixtures/docker/server_manager_nonroot.Dockerfile
Labels: maintenance, !

#305 refactor: rename env vars
  build/compose-node.yaml
  build/compose-sepolia.yaml
  cmd/cartesi-rollups-node/main.go
  cmd/cartesi-rollups-node/services.go
  docs/config.md
  internal/config/generate/Config.toml
  internal/config/get.go
Labels: no changelog, #feat:output-unification

#291 feat: Add Doc on run Node without Docker
  Makefile
  docs/run-natively.md
  setup_env.sh
Labels: no changelog

#312 fix(docker): foundry version
  build/Dockerfile
  build/docker-bake.hcl
Labels: no changelog, #feat:devnet

#326 feat(devnet): add verbose logging argument
  build/Dockerfile
  cmd/gen-devnet/deployer.go
  cmd/gen-devnet/main.go
  cmd/gen-devnet/rollups.go
Labels: no changelog, #feat:devnet
