Repository cartesi/rollups-node, pull requests merged in 2024-01, with the labels that each got.

#203 feat: add configuration documentation
  build/node-compose.yml
  cmd/cartesi-rollups-cli/root/send/send.go
  cmd/cartesi-rollups-node/main.go
  cmd/cartesi-rollups-node/services.go
  docs/config.md
  internal/config/config.go
  internal/config/config_test.go
  internal/config/generate/Config.toml
  internal/config/generate/helpers.go
  internal/config/generate/main.go
  internal/config/get.go
  internal/config/log.go
  internal/config/log_level.go
  internal/config/to_test.go
  internal/logger/logger.go
  internal/services/service.go
Labels: no changelog, #feat:go-supervisor

#216 feat: Add Command to save machine snapshot
  .gitignore
  cmd/cartesi-rollups-cli/root/root.go
  cmd/cartesi-rollups-cli/root/savesnapshot/savesnapshot.go
  docs/cartesi-rollups-cli.md
  docs/cartesi-rollups-cli_save-snapshot.md
  internal/machine/snapshot.go
Labels: no changelog

#227 fix: fix machine snapshot command logger usage
  internal/machine/snapshot.go
Labels: no changelog

#228 Refactor/docker build enhancements
  build/Dockerfile
Labels: no changelog

#226 chore: generate cli docs with go generate command
  cmd/gen-docs/main.go
Labels: no changelog, #feat:rollups-cli

#234 fix: build for Rust 1.75
  offchain/dispatcher/src/drivers/mod.rs
  offchain/host-runner/tests/common/grpc_client.rs
  offchain/host-runner/tests/grpc_tests/get_version.rs
Labels: no changelog

#244 fix: remove unused variables from claimer
  cmd/cartesi-rollups-node/services.go
Labels: no changelog, #feat:go-supervisor, !

#243 fix: forward env vars to redis and server-manager
  cmd/cartesi-rollups-node/services.go
Labels: bug, no changelog, #feat:go-supervisor

#246 fix: prevent segfault error when calling GetCartesiLogTimestamp
  internal/config/config.go
  internal/config/config_test.go
  internal/config/log.go
Labels: no changelog

#261 feat: log healthcheck requests
  cmd/cartesi-rollups-node/services.go
Labels: no changelog

#274 Move inspect api
  README.md
  api/openapi/inspect.yaml
  pkg/inspectclient/main.go
Labels: no changelog, #feat:inspect

#270 Add validate notice command
  CHANGELOG.md
  cmd/cartesi-rollups-cli/root/root.go
  cmd/cartesi-rollups-cli/root/validate/validate.go
  docs/cartesi-rollups-cli.md
  docs/cartesi-rollups-cli_validate.md
  pkg/ethutil/ethutil.go
  pkg/readerclient/proof.go
Labels: #feat:rollups-cli

#277 fix: multi-line logs in Go supervisor
  internal/services/command.go
  internal/services/linewriter.go
  internal/services/linewriter_test.go
Labels: no changelog, #feat:go-supervisor

#279 fix(ci): code quality workflow
  .github/workflows/code-quality.yml
Labels: no changelog

#224 Feature/cmd run deps
  cmd/cartesi-rollups-cli/root/deps/deps.go
  cmd/cartesi-rollups-cli/root/root.go
  docs/cartesi-rollups-cli.md
  docs/cartesi-rollups-cli_deps.md
  docs/cartesi-rollups-cli_deps_start.md
  docs/cartesi-rollups-cli_run-deps.md
  internal/deps/deps.go
Labels: no changelog

#283 chore: remove wrong doc files
  docs/cartesi-rollups-cli_deps.md
  docs/cartesi-rollups-cli_deps_start.md
Labels: no changelog

#284 fix: high RPC usage in dispatcher
  CHANGELOG.md
  offchain/dispatcher/src/dispatcher.rs
  offchain/dispatcher/src/drivers/mock.rs
  offchain/types/src/foldables.rs
Labels: bug, !, #feat:dispatcher

#286 fix(authority-claimer): redact mnemonic from logs
  CHANGELOG.md
  offchain/Cargo.lock
  offchain/authority-claimer/Cargo.toml
  offchain/authority-claimer/src/config/cli.rs
  offchain/authority-claimer/src/config/mod.rs
  offchain/authority-claimer/src/signer/signer.rs
Labels: bug

#285 Add execute voucher command
  CHANGELOG.md
  cmd/cartesi-rollups-cli/root/execute/execute.go
  cmd/cartesi-rollups-cli/root/root.go
  docs/cartesi-rollups-cli.md
  docs/cartesi-rollups-cli_execute.md
  pkg/ethutil/ethutil.go
Labels: #feat:rollups-cli

#293 fix(ci): always run Rust workflow
  .github/workflows/rust-code-quality.yml
Labels: no changelog

#292 fix(cli): execute command endpoint
  cmd/cartesi-rollups-cli/root/execute/execute.go
  docs/cartesi-rollups-cli_execute.md
Labels: no changelog, #feat:rollups-cli
