Repository cartesi/rollups-node, pull requests merged in 2024-07, with the labels that each got.

#505 Update dependencies
  go.mod
  go.sum
Labels: no changelog, maintenance

#519 Add checks to numeric columns in the repository
  internal/repository/base_test.go
  internal/repository/migrations/000001_create_application_input_claim_output_report_nodeconfig.up.sql
Labels: #feat:db

#503 fix(build): update boolean env vars usage
  build/compose-devnet.yaml
  build/compose-node.yaml
  build/compose-sepolia.yaml
Labels: no changelog
